version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: taskmgr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    external: true
    name: task-manager-pro_postgres_data
